
# flags:
#   llvm-hs:
#     shared-llvm: true



resolver: lts-12.2
#nightly-2017-11-04

ghc-options:
  "*": -fdiagnostics-color=always

packages:
- '.'

extra-deps:
- PortMidi-0.1.6.1
- accelerate-1.2.0.0
- accelerate-io-1.2.0.0
- accelerate-llvm-1.2.0.0
- accelerate-llvm-native-1.2.0.0
- arrows-0.4.4.2
- mwc-random-accelerate-0.1.0.0
- Stream-0.4.7.2
- llvm-hs-6.0.0
- llvm-hs-pure-6.0.0
- lazysmallcheck-0.6
- algebraic-graphs-0.1.1.1



